# Site wide configuration

title: This And That
locale: en_US
description: 
logo: 
url: //thisandthat.io

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

comments: true

# Site owner
owner:
  name: Parth Savani
  avatar: this/profile_pic.jpg
  email: parkersavani@gmail.com
  disqus-shortname: thisandthatio
  facebook: parthsavi
  github: parthsavi
  stackexchange:
  linkedin:
  instagram: parthsavi
  flickr:
  pinterest:
  weibo:
  google:
    plus: 103414360754414327764
    analytics: UA-42528026-3
    ad-client: ca-pub-5658878835093489
    ad-slot: 3303642851
